### ISSUE TITLE
Cron Server

### ISSUE THREAD

**Issue by solocommand** [cygnusb2b/base-platform-issues#11]
We need a server set up (or repurposed) to run cron commands. This server will need to utilize the S3 deployment process in use for the webservers to ensure that the latest base-platform code is always available. It doesn't need to run Apache or have any management interface; just a crontab would work.

First entry for generating sitemaps
````
0 0 * * * ACTIVE_CONTEXT=website.*:*/* php /data/localsites/www/base/platform/app/console app_website:sitemap --env=prod
````

**Comment by solocommand** [comment]
For now just use the following:
````
0 0 * * * ACTIVE_CONTEXT=website.alpha:scomm.nfn php /data/localsites/www/base/platform/app/console app_website:sitemap --env=prod
````

Apparently we need to fix some issues with multi-site sitemaps

**Comment by curthusting** [comment]
@solocommand @Jlaird 
What's the status on this one? Do we need it pulled into our new issues bucket?

**Comment by Jlaird** [comment]
I have not done anything with it yet.

**Comment by solocommand** [comment]
@curthusting Yes, it should be pulled over
