### ISSUE TITLE
SOLA Punch List

### ISSUE THREAD

**Issue by solocommand** [cygnusb2b/base-platform-issues#2]
# Remaining
## Website
- [ ] Primary Child Navigation
  - [ ] Desktop 
  - [ ] Colapsed
- [ ] Contact Us Section|Page
- [ ] Advertise Section|Page
- [ ] Directory Landing Page
  - [ ] Product || Company Content Type Filtering
  - [x] Left Hand Navigation (Categories)
   - [x] List of Primary, Secondary, Tertiary...
- [ ] Directory/TermVocab
  - [ ] Product || Company Content Type Filtering (Is this needed???)
 - [x] Product Landing Page
  - [ ] Referring Url TermVocab Filter || Select
  - [ ] Product to Product Scroll
  - [x]  Scroll Into TermVocab Filter
- [ ]  Company Landing Page
  - [ ] Referring Url TermVocab Filter || Select
  - [x] Company RelatedContent Scroll
- [x] Two Col and below support for Left Hand Navigation

**Comment by curthusting** [comment]
@brandonbk do we have designs for the Directory, Company & Product pages?

**Comment by curthusting** [comment]
@B77Mills what is the status of the remaining SOLA requirements? Have any of these been addressed?

**Comment by B77Mills** [comment]
![screen shot 2015-06-26 at 8 07 27 am](https://cloud.githubusercontent.com/assets/3845869/8377852/78b9c27e-1bda-11e5-8e43-3e90aaf5ecb9.png)
![screen shot 2015-06-26 at 8 07 37 am](https://cloud.githubusercontent.com/assets/3845869/8377853/78baee2e-1bda-11e5-8cd7-0c5242f35817.png)

**Comment by curthusting** [comment]
@B77Mills  what is the status of the remaining SOLA requirements? Have any of these been addressed?

**Comment by B77Mills** [comment]
@curthusting  Nope they will be done after the final import to live.  Only because all the section, schedules and content will be whipped prior to the final import, no?

They other stuff, additional Product||Company logic, still needs to be decided.

**Comment by brandonbk** [comment]
Closing this issue, as a start to getting punch lists out of Github.  Individual issues will be created as necessary for anything outstanding.

**Comment by solocommand** [comment]
:+1:
