### ISSUE TITLE
Medical News Punch List

### ISSUE THREAD

**Issue by solocommand** [cygnusb2b/base-platform-issues#3]
# Remaining
## Cleanup
- [x] Regex remove inline styling from paragraph tags on paste AND in all existing body fields/mutations.  `Example: <p style="margin-bottom: 0in;"> should become <p>`
- [ ] Convert csanders@southcomm.com login to cfsanders@southcomm.com; password also changes to cfsanders

## Website
- [x] **JL** Fix DNS for www.saintlouismedicalnews.com
- [x] **BM** Fix line-height issues with "Regulatory & Compliance" block on home page
- [x] Fix whitespace issue with header logos
- [x] Remove Off Call block from home page for all markets EXCEPT East TN
- [ ] Display option for "Contributing Writer" (when they are actually the author)
- [x] Add "Featured Profiles" section to all markets.  Place in nav as second to last item (just before Events).  Get color from Ryan W.  Enable block on home page.
- [x] Add Calendar layout to the Events channel in all markets
- [ ] Add year to date on individual content pages
- [x] Alphabetize sections?  Better sort order?
- [ ] Add site-specific contacts for submit event (work with Cindy Sanders)
- [x] Verify font colors are to spec
- [x] Update MRC pages to include new graphic, body copy
- [ ] Newsletter sign-up
- [ ] Magazine sign-up (basic form? see existing site)
- [x] Verify / fix scheduling for Featured Profiles (examples in email for Memphis) cygnusb2b/base-platform#670

### TBD
- [ ] Collections for Grand Rounds?

**Comment by solocommand** [comment]
@brandonbk Sections are sorted by their sequence field, same as they were in Base2. Need to update sequences in the dev mgmt ui for the order to change as they are all 0.

**Comment by brandonbk** [comment]
Closing; any open items have been moved elsewhere.
